script: "bundle exec rake spec"
language: ruby
rvm:
  - 2.1.2
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:migrate
#  - psql -c 'create database "stck-clinic_test";' -U postgres
